---
# ~/.github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # == /.github/workflows/
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
