---
name: update

on:
  schedule:
    # run every day at 3am
    - cron: '0 3 * * *'

  workflow_dispatch:
    inputs:
      apps:
        description: "Enter apps to process (default is '*')"
        required: false
        default: '*'
      dry:
        description: "Enter 'dry' to do a dry run"
        required: false
        default: ''
      #   force:
      #     description: "Enter 'force' if you want to force a refresh"
      #     required: false
      #    default: 'force'
      options:
        description: "Enter options"
        required: false
        default: ''

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Cache zips
        id: cache-zips
        uses: actions/cache@v3
        with:
          path: ~/cache
          key: cache-key-${{ hashFiles('ziplist.txt') }}

      - name: run actions/setup-python@v4
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: run pip install -r requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run python update.py
        run: python update.py ${{ github.event.inputs.options }}

      - name: save ziplist.txt
        run: |
          ls -ltr cache
          sha256sum cache/*.zip >ziplist.txt

      - name: run foosel/scoop-checkver-action@main
        uses: foosel/scoop-checkver-action@main
        with:
          bucket: bucket
          apps: ${{ github.event.inputs.apps }}
          dry: ${{ github.event.inputs.dry }}
          force: force

      - name: Commit changes
        run: |
          # set git author
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # create individual commit per updated manifest
          while read file; do
            if [[ $file =~ bucket/.*\.json$ ]]; then
              version=$(jq -r .version <$file)
              manifest=$(basename $file .json)
              message="$manifest: Update to version $version"
              git add "$file"
              git commit -m "$message"
            fi
          done < <(git diff --ignore-all-space --name-only --no-color)

      - name: run ad-m/github-push-action@v0.6.0
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
